### ISSUE TITLE
Fix if issue where PR doesn't have `.po` in title or full path (folder/file.po)

### ISSUE THREAD

**Issue by Seluj78** [AFPy/Potodo#12]

**Comment by Seluj78** [comment]
Needs more contextr

**Comment by JulienPalard** [comment]
I think what you meant was sometime people write their issue title as:

- folder/file.html
- folder/file

instead of

- folder/file.po

and that all should be catched by potodo.

**Comment by Seluj78** [comment]
Will be fixed by https://github.com/AFPy/PyDocTeur/pull/57
