### ISSUE TITLE
Potodo is not working on Windows

### ISSUE THREAD

**Issue by Mindiell** [AFPy/Potodo#90]
"NotImplementedError: "Windows" is currently not supported."

**Comment by Mindiell** [comment]
Since I work with this.. "OS", I'll give it a try

**Comment by Seluj78** [comment]
@Mindiell you should only get this error if running potodo in interactive mode (`-i`)

**Comment by Mindiell** [comment]
Nope, got it from the import of simple_term_emu even if I'm not in interactive mode (or is this the default mode ?).
After some research, got it because simple_term_emu is based on termios which seems to be "only available for those Unix versions that support POSIX termios style tty I/O control configured during installation."...

**Comment by Seluj78** [comment]
Hmm ok I see the problem. I'll add a fix soon

**Comment by JulienPalard** [comment]
> But imports in code are ugly I think.

When they fix things, I feel it's acceptable.

It's probably less ugly when used in the right place, typically right after an `if is_interactive` may not be the best place, but as a first line of the only function needing it feels OK to me.

I typically enjoy having `import argparse` in the only function using it, to avoid importing it when it's not needed (when used as a library).

So, same here, if imported in the only function using it, when the program is called without `-i` it won't be imported. It's probably a few milliseconds faster not to import it, so it's not only a gain for Windows users, it becomes a gain for everyone.

**Comment by Seluj78** [comment]
@JulienPalard got time to issue a fix ?

**Comment by JulienPalard** [comment]
Not today, gotta sleep, but I hope so.

**Comment by Seluj78** [comment]
@Mindiell can you try updating potodo with 

```
pip install git+https://github.com/JulienPalard/potodo.git@windows-compatibility
```
