### ISSUE TITLE
What is cache_args?

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/Potodo#94]
I don't understand what this variable is. But it looks a good source of "full caches reset", which looks bad to me.

**Comment by Seluj78** [comment]
`cache_args` is a dict containing all of the arguments values and if, when cache is loaded, the cache_args from the cache are different than from what was passed in execution, then the cache is ignored and loaded again

**Comment by JulienPalard** [comment]
> then the cache is ignored and loaded again

but, why ?

**Comment by Seluj78** [comment]
By that i mean if the args are different, then the result will be different so the cache is scrapped and all the files are read again

**Comment by JulienPalard** [comment]
But it looks like we're caching `PoFileStats` instances which have a single parameter `po_file`, so how could they vary with the other arguments?

**Comment by Seluj78** [comment]
The exclude argument for example, which will remove some files from the cached files

**Comment by Seluj78** [comment]
Closing it for now
